spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelmanagement
    username: postgres
    password: Tantran308@@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c8e271ee91a3421a508e
            client-secret: a5e5a8ab14f87b8efcdbd24b5e89e1af0518d04f
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

frontend:
  url=http://localhost:3000:
